Fix missing string in static_assert()
The clang-18 reported following compilation issue:
third_party/graphFile-schema/vpux_elf/loader/src/managed_buffer.cpp:16:50:
error: 'static_assert' with no message is a C++17 extension
[-Werror,-Wc++17-extensions]
static_assert(sizeof(size_t) >= sizeof(uintptr_t));

Fixed it by adding empty message to static_assert.